let current=1;
const $=s=>document.querySelector(s);
function show(n){current=n;document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',+x.dataset.screen===n));document.querySelectorAll('.step').forEach((x,i)=>{x.classList.toggle('active',i+1===n);x.classList.toggle('complete',i+1<n);if(i+1<n)x.querySelector('b').textContent='✓';else x.querySelector('b').textContent=i+1;});}
document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>show(Math.min(4,current+1)));
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show(Math.max(1,current-1)));
$('#showKey').onclick=()=>{const i=$('#apiKey');i.type=i.type==='password'?'text':'password';$('#showKey').textContent=i.type==='password'?'Show':'Hide'};
$('#test').onclick=async()=>{const key=$('#apiKey').value.trim(),box=$('#testStatus'),button=$('#test');box.hidden=false;box.className='test-status';box.textContent='Testing your connection…';button.disabled=true;const settings={provider:'openrouter',endpoint:'https://openrouter.ai/api/v1/chat/completions',apiKey:key,model:$('#model').value};try{const result=await chrome.runtime.sendMessage({type:'TEST_CONNECTION',settings});if(!result?.ok)throw new Error(result?.error||'Connection failed');await chrome.storage.local.set(settings);box.textContent='✓ Connected successfully';$('#connectNext').disabled=false}catch(e){box.className='test-status error';box.textContent=e.message}finally{button.disabled=false}};
$('#connectNext').onclick=async()=>{await chrome.storage.local.set({provider:'openrouter',endpoint:'https://openrouter.ai/api/v1/chat/completions',apiKey:$('#apiKey').value.trim(),model:$('#model').value});show(3)};
document.querySelector('[data-screen="3"] [data-next]').onclick=async()=>{await chrome.storage.local.set({language:$('#language').value,enabled:$('#enabled').checked,onboardingComplete:true});show(4)};
$('#settings').onclick=()=>chrome.runtime.openOptionsPage();
$('#finish').onclick=()=>{chrome.tabs.create({url:'https://web.whatsapp.com'});window.close()};
(async()=>{const s=await chrome.storage.local.get({model:'openai/gpt-4o-mini',language:'English',enabled:true,apiKey:''});$('#apiKey').value=s.apiKey||'';$('#model').value=[...$('#model').options].some(o=>o.value===s.model)?s.model:'openai/gpt-4o-mini';$('#language').value=s.language;$('#enabled').checked=s.enabled;if(s.apiKey)$('#connectNext').disabled=false})();
